### PR TITLE
[WIP] Add paper patch

### PR DESCRIPTION
**Pull request by Romaindu35**
I am in the process of adding the paper api / patch patches
You can see the patch being added / being added on this google doc :
https://docs.google.com/spreadsheets/d/1kecEC5bzdcP6VsAoDDa_xbzHEgj-qE3EvResmhw2Ayw/edit?usp=sharing

### CODE REVIEW

**Comment by Romaindu35** [comment]
This pr was not ready to be merged that's why I had marked it wip. I think there must be some bugs left.

**Comment by KR33PYK1NG** [comment]
> 
> 
> This pr was not ready to be merged that's why I had marked it wip. I think there must be some bugs left.

Thanks for informing, I've reverted the changes. They most certainly did cause new issues.

**Comment by KR33PYK1NG** [comment]
Feel free to reopen your PR, but be more explicit about it being work-in-progress.
I've talked to InkerBot, he said he didn't understand what WIP means.

**Comment by Romaindu35** [comment]
Ok sorry

**Pull request merged**
