### PR TITLE
Add Forge -> Bukkit Call (Forge mods can call plugin class)

### PR DESCRIPTION
**Pull request by terrainwax**
Classloader now know is Child and can acces to her class

### CODE REVIEW

**Comment by terrainwax** [comment]
[ProofOfWork.zip](https://github.com/Mohist-Community/Mohist/files/3893670/ProofOfWork.zip)
this files can be use to test 

a command test is add when you use it , this add you 100dollars on you account

**Comment by Mgazul** [comment]
This breaks the nms remapping function and therefore cannot return the superclass
@terrainwax

**Comment by terrainwax** [comment]
I will take a look

**Comment by terrainwax** [comment]
Can i have the plugin who are break or how reproduce the break to fix it @Mgazul

**Comment by Mgazul** [comment]
Citizens2  /npc create name ,Unable to get getName from EntityPlayerMP superclass Entity

**Pull request merged**
