### PR TITLE
Auto delete/fix mods and plugins (100%)

### PR DESCRIPTION
**Pull request by Romaindu35**
Continuation of the PR : https://github.com/Mohist-Community/Mohist/pull/1189

I have added a system to dowload fix mods

### CODE REVIEW

**Comment by Shawiizz** [comment]
I don't think this is useful since we don't create fix for mods.

**Comment by Romaindu35** [comment]
> I don't think this is useful since we don't create fix for mods.

But if someone creates one

**Comment by Romaindu35** [comment]
I also modified the plugin fix to take into account all the essential jars

**Comment by Mgazul** [comment]
Considering that discord is not accessible in some countries, it is not recommended to use https://cdn.discordapp.com as the address for downloading files

**Comment by Romaindu35** [comment]
> Considering that discord is not accessible in some countries, it is not recommended to use https://cdn.discordapp.com as the address for downloading files

I did like that, because it had been done like that in 1.12 (https://github.com/Mohist-Community/Mohist/blob/1.12.2/src/main/java/com/mohistmc/bukkit/AutoDeletePlugins.java#L19) , I was thinking of the possibility of adding the mods / plugins fix on the site

**Comment by Shawiizz** [comment]
Then I'll upload all fixes on my VPS so that it uses mohistmc.com domain

**Comment by Romaindu35** [comment]
for now I leave it like that?

**Comment by Shawiizz** [comment]
Yes, i will change the links myself

**Pull request closed without merging**
