### PR TITLE
1.15.2

### PR DESCRIPTION
**Pull request by 1798643961**
打完Bukkit-Patches部分

### CODE REVIEW

**Comment by kingdevnl** [comment]
@1798643961 Stop stealing code, dude.

If you don't stop i'm going to send a DMCA to this repo

**Comment by F4JBS** [comment]
@kingdevnl 
Which license is your code released under? Mohist is GPLv3 and compatible with most libre licenses.

**Comment by kingdevnl** [comment]
GNU General Public License v2.0

They are beaking our Copyright as they don't credit us for the work that took us Months to do..

**Comment by TansuoTro** [comment]
# As you can see, this PR does not contain any Magma code

**Pull request merged**
