### PR TITLE
Include both Commons-lang 2.6 and 3.3.2 into Mohist

### PR DESCRIPTION
**Pull request by Irgendwer01**
Fixes Compatibility with the Pack Gregtech: New Horizons in future but not breaks other packs.
Both can co-exist since they have different classpaths.

### CODE REVIEW

**Review by MCUmbrella — APPROVED** [review]

**Comment by Shawiizz** [comment]
Hi, if you want to include it to the server, you also need to add it in the libraries txt file. Here you just added it to Gradle

**Comment by Shawiizz** [comment]
This library doesn't exists in the Mohist's maven. Let me add it

**Review by Shawiizz — COMMENTED** [review]
The changes souldn't be made in build.gradle since we don't need it in IDE.

**Comment by Shawiizz** [comment]
I added it myself. I close this pr ^^

**Pull request closed without merging**
